[project]
name = "local-agentic-ai"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.116.1",
    "ollama>=0.5.3",
    "uvicorn>=0.35.0",
]
